### ISSUE TITLE
configurable UI

### ISSUE THREAD

**Issue by pseudozach** [chill117/passport-lnurl-auth#8]
Is it possible to make the UI more configurable like leave out certain sections? or is it possible to access only  the QR code and serve that to user in my own UI?

**Comment by chill117** [comment]
> Is it possible to make the UI more configurable like leave out certain sections? or is it possible to access only the QR code and serve that to user in my own UI?

I've added a new middleware option ("loginTemplateFilePath") which you can use to provide the file path to your own custom login.html file. You can use the [login.html](https://github.com/chill117/passport-lnurl-auth/blob/master/templates/login.html) included in this repo as a starting point or guide to create your custom login.html

The latest release v1.5.0 has the new middleware option.

**Comment by pseudozach** [comment]
perfect thanks, I'll give it a try. I didn't notice it in the readme.
